# Use a standard Python image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy all your project files into the container
COPY . .

# Install the Python dependencies from your requirements.txt file
RUN pip install -r requirements.txt

# The command to run when the container starts.
# This is modified to run Streamlit on the required port.
CMD ["streamlit", "run", "CLIP_app.py", "--server.port=7860", "--server.address=0.0.0.0"]