# Use a standard Python image
FROM python:3.11

# Set the working directory inside the container
WORKDIR /app

# Copy all your project files into the container
COPY . .

# Install the Python dependencies from your requirements.txt file
RUN pip install -r requirements.txt

# Expose the port that Streamlit runs on
EXPOSE 8501

# The command to run when the container starts
CMD ["streamlit", "run", "CLIP_app.py"]